# Generated by Django 3.0 on 2020-04-17 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('administrator', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('govner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chefZoneLeader', models.CharField(max_length=30)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Commune')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('chefQuarter', models.CharField(max_length=30)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('Prenom', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('NomPere', models.CharField(max_length=20)),
                ('NomMere', models.CharField(max_length=20)),
                ('colline', models.CharField(max_length=20)),
                ('commune_natal', models.CharField(max_length=20)),
                ('province_natal', models.CharField(max_length=20)),
                ('anneeDeNaissance', models.CharField(max_length=20)),
                ('nationalite', models.CharField(max_length=20)),
                ('etatCivil', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('numberId', models.CharField(max_length=20)),
                ('date_delivrated', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdentiteComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attestionId', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Person')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Commune')),
                ('provine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Province')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Quarter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idcomplete.Province'),
        ),
    ]
