# Generated by Django 3.0 on 2020-04-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcomplete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='province',
        ),
        migrations.RemoveField(
            model_name='quarter',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='commune',
        ),
    ]
