# Generated by Django 3.0 on 2020-04-18 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idcomplete', '0002_auto_20200418_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitecomplete',
            old_name='provine',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='identitecomplete',
            name='Person',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='idcomplete.Person'),
        ),
        migrations.AlterField(
            model_name='identitecomplete',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
